
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'microservices'
    static_configs:
      - targets:
          - 'orders-service:5001'
          - 'payments-service:5002'
          - 'logs-service:5003'
          - 'notifications-service:5004'
          - 'metricas-service:5005'
    metrics_path: '/metrics'
    scrape_interval: 10s
