version: "3.9"

services:

  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    depends_on:
      - orders
      - payments
      - notifications
      - logs
      - metricas

  orders:
    build: ./orders
    ports:
      - "5001:5001"

  payments:
    build: ./payments
    ports:
      - "5002:5002"

  notifications:
    build: ./notifications
    ports:
      - "5003:5003"

  logs:
    build: ./logs
    ports:
      - "5004:5004"

  metricas:
    build: ./metricas
    ports:
      - "5005:5005"
