version: "3.9"

services:
  # ---------------- POSTGRES ----------------
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sysd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network
    restart: unless-stopped

  # ---------------- ORDERS ----------------
  orders:
    build: ./orders
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    networks:
      - microservices-network
    restart: unless-stopped

  # ---------------- PAYMENTS ----------------
  payments:
    build: ./payments
    ports:
      - "5002:5002"
    depends_on:
      - postgres
    networks:
      - microservices-network
    restart: unless-stopped

  # ---------------- LOGS ----------------
  logs:
    build: ./logs
    ports:
      - "5003:5003"
    networks:
      - microservices-network
    restart: unless-stopped

  # ---------------- NOTIFICATIONS ----------------
  notifications:
    build: ./notifications
    ports:
      - "5004:5004"
    networks:
      - microservices-network
    restart: unless-stopped

  # ---------------- METRICAS ----------------
  metricas:
    build: ./metricas
    ports:
      - "5005:5005"
    networks:
      - microservices-network
    restart: unless-stopped

  # ---------------- API GATEWAY ----------------
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - orders
      - payments
      - logs
      - notifications
      - metricas
    networks:
      - microservices-network
    restart: unless-stopped

  # ---------------- PROMETHEUS ----------------
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - microservices-network
    restart: unless-stopped

  # ---------------- GRAFANA ----------------
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - microservices-network
    restart: unless-stopped

  # ---------------- LOKI ----------------
  loki:
    image: grafana/loki:2.8.2
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki/loki-config.yaml:/etc/loki/config.yaml
    command: -config.file=/etc/loki/config.yaml
    networks:
      - microservices-network
    restart: unless-stopped

  # ---------------- PROMTAIL ----------------
  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./monitoring/promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - microservices-network
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres_data:
